# Generated by Django 4.2.6 on 2024-01-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company',
            new_name='owner',
        ),
    ]
