# Generated by Django 5.0.1 on 2024-01-24 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_company_company_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invitation_code',
            new_name='InvitationCode',
        ),
    ]
