# Generated by Django 4.2.6 on 2024-02-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_timetable_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='upload',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
