# Generated by Django 4.2.6 on 2024-02-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_availability_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='upload',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
