# Generated by Django 4.2.6 on 2024-02-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_availability_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='availability_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='availability_start',
            field=models.DateTimeField(),
        ),
    ]
