# Generated by Django 4.2.6 on 2024-02-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_availability_availability_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='availability_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='availability_start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start',
            field=models.TimeField(),
        ),
    ]
