# Generated by Django 4.2.6 on 2024-02-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_timetablesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablesettings',
            name='people',
            field=models.IntegerField(default=2),
        ),
    ]
